# Generated by Django 5.1.5 on 2025-01-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_officeappuser_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='officeappuser',
            table='office_app_user',
        ),
    ]
