# Generated by Django 5.1.5 on 2025-01-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_officeappuser_isauthenticated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeappuser',
            name='isAuthenticated',
        ),
    ]
