# Generated by Django 5.1.5 on 2025-01-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_reservation_timetable_alter_officeappuser_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('name', 'room', 'code', 'from_datetime', 'to_datetime')},
        ),
    ]
