# Generated by Django 5.2 on 2025-05-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': False},
        ),
    ]
