# Generated by Django 5.1.5 on 2025-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_officeappuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeappuser',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeappuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='officeappuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='officeappuser',
            name='permissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='officeappuser',
            table=None,
        ),
    ]
