# Generated by Django 5.1.5 on 2025-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_officeappuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField(default=90)),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('group', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=9)),
                ('code', models.CharField(max_length=9)),
                ('duration_minutes', models.IntegerField()),
                ('from_datetime', models.DateTimeField()),
                ('group', models.CharField(max_length=20)),
                ('is_canceled', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=7)),
                ('user', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
        migrations.AlterModelTable(
            name='officeappuser',
            table='office_app_user',
        ),
    ]
