# Generated by Django 4.2.16 on 2025-07-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_reservation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeAppUser',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='is_canceled',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='timetable',
        ),
    ]
